from moves import *
from effects import *

skill_tree = dict()
skill_tree["magic-bolt"] = dict()
skill_tree["magic-bolt"]["fireball"] = dict()
skill_tree["magic-bolt"]["fireball"]["lava-burst"] = dict()
skill_tree["magic-bolt"]["fireball"]["lava-burst"]["solar-flare"] = dict()
skill_tree["magic-bolt"]["fireball"]["lava-burst"]["flash-inferno"] = dict()
skill_tree["magic-bolt"]["fireball"]["cinder-barrage"] = dict()
skill_tree["magic-bolt"]["fireball"]["cinder-barrage"]["melting-strike"] = dict()
skill_tree["magic-bolt"]["fireball"]["cinder-barrage"]["hot-blaze"] = dict()
skill_tree["magic-bolt"]["ice-blast"] = dict()
skill_tree["magic-bolt"]["ice-blast"]["artice-lance"] = dict()
skill_tree["magic-bolt"]["ice-blast"]["artice-lance"]["deep-freeze"] = dict()
skill_tree["magic-bolt"]["ice-blast"]["artice-lance"]["encase"] = dict()
skill_tree["magic-bolt"]["ice-blast"]["flash-freeze"] = dict()
skill_tree["magic-bolt"]["ice-blast"]["flash-freeze"]["pierce"] = dict()
skill_tree["magic-bolt"]["ice-blast"]["flash-freeze"]["blizzard"] = dict()
skill_tree["magic-bolt"]["thorn"] = dict()
skill_tree["magic-bolt"]["thorn"]["poison"] = dict()
skill_tree["magic-bolt"]["thorn"]["drain"] = dict()
skill_tree["heal"] = dict()

abilities = dict()
abilities["attack"] = Damage("attack")
abilities["block"] = CastEffectSelf("block", Block, 3, "[caster] has taken a defensive stance")
abilities["magic-bolt"] = MagicDamage("magic-bolt", "magic", 0.8, 1.0)
abilities["fireball"] = MagicDamage("fireball", "fire", 1, 1.0)
abilities["lava-burst"] = MagicDamage("lava-burst", "fire", 1, 1.5)
abilities["solar-flare"] = Recoil(MagicDamage("solar-flare", "fire", 1, 3.0), "fire", 0.1)
abilities["cinder-barrage"] = CastDynamicEffect(MagicDamage("cinder-barrage", "fire", 1, 1.2), Burn, 3, "[target] was burned.", 0.1)
abilities["melting-strike"] = CastEffect(MagicDamage("melting-strike", "fire", 1, 1.0), ReduceArmor, 3, "[target]'s defense was lowered by 20%", 0.8, "melted")
abilities["flash-inferno"] = CastDynamicEffect(MagicDamage("flash-inferno", "fire", 1, 0.6), Combo, 2, "", "flash-inferno", 1.5)
abilities["hot-blaze"] = CastEffect(MagicDamage("hot-blaze", "fire", 1, 1.0), Amplify, 4, "Fire resistance lowered by 40%.", "fire", 1.4, "decrease-fire-resistance")
abilities["ice-blast"] = CastEffect(MagicDamage("ice-blast", "frost", 0.8, 1.0), Slow, 2, "[target] was slowed.", 0.5)
abilities["arctic-lance"] = Compare("arctic-lance", lambda caster, target: True if caster.get_speed() > target.get_speed() else False, MagicDamage("arctic-lance", "frost", 0.8, 3.0), MagicDamage("arctic-lance", "frost", 0.8, 1.0))
abilities["flash-freeze"] = CastEffectSelf(MagicDamage("flash-freeze", "frost", 0.8, 1.0), Block, 3, "[caster] gained 20% fire resistance", 0.8, "fire", "chilled")
abilities["blizzard"] = Message(Repeat(MagicDamage("blizzard", "frost", 0.8, 0.4), 5), "[caster] unleashes a barrage of ice: ", True)
abilities["deep-freeze"] = CastEffect(MagicDamage("deep-freeze", "frost", 1, 1.0), IncreaseDefense, 3, "[target] was in encased in ice", 1.3, "Frost Armor")
abilities["encase"] = CastEffect(MagicDamage("encase", "frost", 1, 4.0), ReduceAttack, 3, "[target]'s attack was crippled.", 0.8, "Frost Armor")
abilities["pierce"] = MagicDamage("pierce", "true", 0.8, 0.8)
abilities["thorn"] = MagicDamage("thorn", "nature", 0.6, 1.2)
abilities["drain"] = HealSelf(MagicDamage("thorn", "nature", 0.6, 1.0), 0.2, 0.5)
abilities["poison"] = CastDynamicEffect(MagicDamage("poison", "nature", 0.6, 0.5), Poison, 3, "[target] was poisoned.", 0.2)
abilities["heal"] = Heal("heal", 0.8, 1)